server:
  port: 8080
  contextPath: /SpringBoot

spring:
  profiles:
    active: h2
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    #jdbc:h2:file:./accounts.db --- to Use local xml based database
  jpa:
    hibernate:
      ddl-auto: update


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/
#    username: root
#    password: root
    #driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#Mysql config
